pipeline:
  build:
    image: ubuntu:xenial
    commands:
      - apt update
      - apt install -y git sudo python-pip python-minimal software-properties-common
      - pip install ansible
      - apt-get -y clean && apt-get -y autoclean
      - ansible-playbook -i "127.0.0.1,"  tests/test.yml --syntax-check
      - ansible-playbook -i "127.0.0.1," tests/test.yml --connection=local --become
      - >
        ansible-playbook -i "127.0.0.1," tests/test.yml --connection=local --become
        | grep -q 'changed=9.*failed=0'
        && (echo 'Idempotence test: pass' && exit 0)
        || (echo 'Idempotence test: fail' && exit 1)
      - systemctl status django_example_app.service
      - echo $?
  notify:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [success, failure]
      event: [push, tag]