pipeline:
  build:
    image: ubuntu:xenial
    commands:
      - apt update
      - apt install -y git sudo python-pip python-minimal software-properties-common curl apt-transport-https
      - pip install ansible
      - apt-get -y clean && apt-get -y autoclean
      - ansible-playbook -i "127.0.0.1," tests/test.yml --syntax-check
      - ansible-playbook -i "127.0.0.1," tests/test.yml --connection=local --become
    secrets: [ git_key ]
  notify:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [success, failure]
      event: [push, tag]
