---
- name: Copy environment variables file
  template:
    src: env.j2
    dest: "{{ react_local_checkout_path }}/.env"
  delegate_to: 127.0.0.1
  become: false

- name: Install Javascript requirements
  shell: "yarn install"
  args:
    chdir: "{{ react_local_checkout_path }}"
  environment:
    PATH: "$PATH:{{ react_local_yarn_binary_dir }}"
  become: false
  delegate_to: 127.0.0.1

- name: Compile Javascript
  shell: "yarn build"
  args:
    chdir: "{{ react_local_checkout_path }}"
  environment:
    PATH: "$PATH:{{ react_local_yarn_binary_dir }}"
  become: false
  delegate_to: 127.0.0.1

- name: Compress Build folder
  archive:
    path: "{{ react_local_build_path }}"
    dest: "{{ react_local_build_path }}.tgz"
  become: false
  delegate_to: 127.0.0.1

- name: UnCompress Build folder
  unarchive:
    src: "{{ react_local_build_path }}.tgz"
    dest: "{{ react_checkout_path }}"
  become: True
  become_user: "{{ react_system_user }}"

- name: Make the new codebase current
  file:
    src: "{{ react_checkout_path }}"
    dest: "{{ react_codebase_path }}"
    state: link
    force: yes
    owner: "{{ react_system_user }}"
    group: "{{ react_system_group }}"
