---
- name: Copy environment variables file
  template:
    src: env.j2
    dest: "{{ react_app_path }}/.env"
    mode: 0644
    owner: "{{ react_system_user }}"
    group: "{{ react_system_group }}"

- name: Install Javascript requirements
  shell: yarn install
  args:
    chdir: "{{ react_app_path }}"
  become: True
  become_user: "{{ react_system_user }}"

- name: Compile Javascript
  shell: yarn build
  args:
    chdir: "{{ react_app_path }}"
  become: True
  become_user: "{{ react_system_user }}"

- name: Make the new codebase current
  file:
    src: "{{ react_checkout_path }}"
    dest: "{{ react_codebase_path }}"
    state: link
    force: yes
    owner: "{{ react_system_user }}"
    group: "{{ react_system_group }}"
