---
- name: Remote Compile
  block:
    - name: Copy environment variables file
      template:
        src: env.j2
        dest: "{{ react_checkout_path }}/.env"
        mode: 0644
        owner: "{{ react_system_user }}"
        group: "{{ react_system_group }}"

    - name: Install Javascript requirements
      command: yarn install
      args:
        chdir: "{{ react_checkout_path }}"
      become: True
      become_user: "{{ react_system_user }}"

    - name: Compile Javascript
      command: yarn build
      args:
        chdir: "{{ react_checkout_path }}"
      become: True
      become_user: "{{ react_system_user }}"

    - name: Make the new codebase current
      file:
        src: "{{ react_checkout_path }}"
        dest: "{{ react_codebase_path }}"
        state: link
        force: yes
        owner: "{{ react_system_user }}"
        group: "{{ react_system_group }}"
  when: "react_remote_js_build|bool"

- name: Local Compile
  block:
    - name: Copy environment variables file
      template:
        src: env.j2
        dest: "{{ react_local_checkout_path }}/.env"
      delegate_to: 127.0.0.1
      become: false

    - name: Install Javascript requirements
      command: yarn install
      args:
        chdir: "{{ react_local_checkout_path }}"
      become: false
      delegate_to: 127.0.0.1

    - name: Compile Javascript
      command: yarn build
      args:
        chdir: "{{ react_local_checkout_path }}"
      become: false
      delegate_to: 127.0.0.1

    - name: Compress Build folder
      archive:
        path: "{{ react_local_checkout_path }}/build"
        dest: "{{ react_local_checkout_path }}/build.tgz"
      become: false
      delegate_to: 127.0.0.1

    - name: UnCompress Build folder
      unarchive:
        src: "{{ react_local_checkout_path }}/build.tgz"
        dest: "{{ react_checkout_path }}"
      become: True
      become_user: "{{ react_system_user }}"

    - name: Make the new codebase current
      file:
        src: "{{ react_checkout_path }}"
        dest: "{{ react_codebase_path }}"
        state: link
        force: yes
        owner: "{{ react_system_user }}"
        group: "{{ react_system_group }}"

  when: "not react_remote_js_build|bool"
